config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root to: "events#index"

   devise_for :users
   get '/users', to: "events#index"
   get '/users/:id', to: 'users#show', as: 'user' 

   resources :events
   resources :invites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :date, presence: true
  validates :body, presence: true
  validates :location, presence: true

  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }

  belongs_to :creator, class_name: :User, foreign_key: :creator_id
  has_many :invites
  has_many :attendees, through: :invites, source: :user
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: :creator_id   
  has_many :invites
  has_many :attended_events, through: :invites, source: :event    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]

  def index
    @past_events = Event.includes(:creator).past
    @upcoming_events = Event.includes(:creator).upcoming
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash.notice = "#{@event.title} was successfully created."
      redirect_to :root
    else 
      render :new, status: :unprocessable_entity
    end    
  end

  def show
    @event = Event.find(params[:id])
    @current_guests = @event.attendees.all
  end

  private
  
  def event_params
    params.require(:event).permit(:title, :body, :date, :location )
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def new
    @invite = current_user.invites.build
  end

  def create
    @invite = current_user.invites.build(inivitation_params)
    
    if @invite.save
      flash[:notice] = 'You joined the event!'
      redirect_to event_path(params[:invite][:event_id])
    else 
      render :new, status: :unprocessable_entity
    end      
  end

  private

  def inivitation_params
    params.require(:invite).permit(:event_id, :user_id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action 
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else 
        redirect_to navigation_location  
      end  
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  before_action :authenticate_user!, except: %i[index show]

  def show
    @hosted_events = @user.events.all
    @attend_events = @user.attended_events
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_invitation_form.html.erb
<%= form_with model: Invite.new do |form| %>
  <%= form.hidden_field :event_id, :value => @event.id %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.submit "Join Event" %>
<% end %>

app/views/events/_invitation_process.html.erb
<% if user_signed_in? %>
  <%= render 'invitation_form' %>
<% else %>
  <p><em>Log in to attend this event.</em></p>
<% end %>  

app/views/events/index.html.erb
<h1>Events</h1>

  <% @upcoming_events.each do |event| %>
    <h3><%= link_to event.title, event_path(event) %></h3>
    <p> <%= event.body %> </p>
    <p> <%= event.date %>, <%= event.location %> </p>
  <% end %>  

<h2>Past Events</h2>

<% @past_events.each do |event| %>
    <h3><%= link_to event.title, event_path(event) %></h3>
    <p> <%= event.body %> </p>
    <p> <%= event.date %>, <%= event.location %> </p>
  <% end %>  

app/views/events/new.html.erb
<h1>New Event</h1>

<% if @event.errors.any? %>
  <h3><%= pluralize(@post.errors.count, 'error') %> prohibited this event from being saved: </h3>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
  </ul>
<% end %> 

<%= form_with model: @event do |form| %>
  <%= form.label :title, 'Title: ' %>
  <%= form.text_field :title %>
  <%= form.label :body, 'Describe event: ' %>
  <%= form.text_area :body %>
  <%= form.label :date, 'Date: ' %>
  <%= form.date_field :date %>
  <%= form.label :location, 'Location: ' %>
  <%= form.text_field :location %>
  <%= form.submit 'Create Event' %>
<% end %>

app/views/events/show.html.erb
<h2> <%= @event.title %> </h2>

<p>
  <strong>Event date:</strong> <%= @event.date %><br>
  <strong>Event location:</strong> <%= @event.location %><br>
  <strong>Event description:</strong> <%= @event.body %><br>
  <strong>Hosted by:</strong> <%= @event.creator.name %><br>

  <% unless @current_guests[0].nil? %>
    <strong>Current guests: </strong>
    <ul>
    <% @current_guests.each do |guest| %>
      <li><%= guest.name %></li>
    <% end %>
    </ul><br>
  <% end %>
  
    <% if @event.attendees.include?(current_user) %>
      You've already joined this event! 
    <% else %>
      <%= render 'invitation_process' %>
    <% end %>

</p>  
<%= link_to '<-- Back', 'javascript:history.back()' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= link_to 'Home', root_path %>

    <% if user_signed_in? %>
      <h2>Welcome, <%= current_user.name %></h2>
      <%= link_to 'Create New Event', new_event_path %>
      <%= link_to 'My Events', user_path(current_user) %>
      <%= link_to 'Click here to logout', destroy_user_session_path, data: { turbo_method: :delete } %>
    <% else %>  
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>  

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h2>Your Hosted Events</h2>
<p>
  <% if @hosted_events.nil? %>
      You haven't created any events yet!
  <% else %>  
    <% @hosted_events.each do |event| %>
        <h3><%= link_to event.title, event_path(event) %></h3>
      <p>  <%= event.date %>, <%= event.location %> </p>
      <p>  <%= event.body %> </p>
    <% end %>  
  <% end %>
</p>

<h2>Future Events to Attend</h2>
<p>
  <% if @attend_events.nil? %>
      You aren't going to any events yet!
  <% else %>  
    <% @attend_events.upcoming.each do |event| %>
        <h3><%= link_to event.title, event_path(event) %></h3>
    <% end %>  
  <% end %>
</p>

<h2>Past Events You've Attended</h2>
<p> 
    <% @attend_events.past.each do |event| %>
        <h3><%= link_to event.title, event_path(event) %></h3> 
  <% end %>
</p>

<%= link_to '<-- Back', root_path %>